[tool.poetry]
name = "my-lms"
version = "0.1.0"
description = "Telegram bot"
authors = ["Nikolnik24 <nikolaxdowork@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "*"
aiogram = "^3.0.0"
pydantic-settings = "*"
uvicorn = "*"
sqlalchemy = "^2.0.54"
alembic = "^1.20.0"
asyncpg = "^0.31.0"
passlib = "^1.7.4"
bcrypt = "4.3.0"
flet = "^1.0.1"
httpx = "^0.28.1"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
redis = "^5.0"
arq = "^0.28"
python-multipart = ">=0.0.9"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-asyncio = "*"
fakeredis = "^2.24"
aiosqlite = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
