"""stage1-5_schema

Revision ID: f37475523ce0
Revises: 40d0c116f436
Create Date: 2026-10-01 12:18:52.002159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37475523ce0'
down_revision: Union[str, Sequence[str], None] = '40d0c116f436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=now(): функция Postgres; на SQLite её нет. Для переносимости
    # (CI/локальная проверка миграций на SQLite) ставим CURRENT_TIMESTAMP — она
    # есть в обеих СУБД. Заполнение существующих строк — тем же значением.
    op.add_column('homeworks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('ix_homeworks_lesson_id', 'homeworks', ['lesson_id'], unique=False)
    op.add_column('lessons', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('board_url', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('ix_lessons_start_time', 'lessons', ['start_time'], unique=False)
    op.create_index('ix_lessons_student_id', 'lessons', ['student_id'], unique=False)
    op.add_column('mock_exams', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('ix_mock_exams_student_id', 'mock_exams', ['student_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    if op.get_bind().dialect.name == "postgresql":
        # Уникальность telegram_id: в initial-миграции колонка создана без UNIQUE,
        # добавляем именованное ограничение (в модели объявлено unique=True).
        # На SQLite ALTER ... ADD CONSTRAINT не поддерживается вообще
        # (NotImplementedError), а уникальность там не критична — это только
        # локальные прогоны миграций; боевая база — Postgres.
        op.create_unique_constraint('uq_users_telegram_id', 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.drop_constraint('uq_users_telegram_id', 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_index('ix_mock_exams_student_id', table_name='mock_exams')
    op.drop_column('mock_exams', 'created_at')
    op.drop_index('ix_lessons_student_id', table_name='lessons')
    op.drop_index('ix_lessons_start_time', table_name='lessons')
    op.drop_column('lessons', 'created_at')
    op.drop_column('lessons', 'board_url')
    op.drop_column('lessons', 'video_url')
    op.drop_index('ix_homeworks_lesson_id', table_name='homeworks')
    op.drop_column('homeworks', 'created_at')
    # ### end Alembic commands ###
