/** Все тексты интерфейса (русский). Источник: docs/07_design.md */

export const texts = {
  common: {
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    create: "Создать",
    close: "Закрыть",
    back: "Назад",
    next: "Далее",
    confirm: "Подтвердить",
    loading: "Загрузка…",
    error: "Ошибка",
    retry: "Повторить",
    empty: "Пусто",
    yes: "Да",
    no: "Нет",
  },

  auth: {
    loginTitle: "Вход в Ромчик | ИнфоМат",
    loginSubtitle: "Войди через Telegram-бота",
    loginButton: "Войти",
    loginWithLink: "Вход по одноразовой ссылке",
    invalidLink: "Ссылка недействительна или устарела. Попроси новую у Романа",
    openInBot: "Открой приложение через бота @{botUsername}",
  },

  schedule: {
    empty: "Пока уроков нет. Роман добавит расписание, и оно появится здесь",
    today: "Сегодня",
    tomorrow: "Завтра",
    upcoming: "Ближайшие",
    noLessons: "Нет уроков",
    telemost: "Телемост",
    board: "Доска",
    lessonIn: "через",
    minutes: "мин",
    hours: "ч",
  },

  homework: {
    empty: "Все ДЗ сделаны. Новые появятся здесь",
    active: "Активные",
    submitted: "На проверке",
    graded: "Проверено",
    expired: "Сгорело",
    submit: "Сдать",
    selfReport: "Сделал",
    selfReportHint: "Для устных заданий и задач на других платформах",
    submitSuccess: "ДЗ отправлено на проверку",
    deadline: "Сдать до {date}, {time}",
    overdue: "Срок вышел. Напиши Роману",
    expiredText: "Срок сдачи закончился, сдать уже нельзя",
    needsRevision: "Нужно доработать. Комментарий ниже",
    fileLimit: "Можно загрузить до 10 файлов",
    fileSize: "Файл больше 10 МБ",
    fileType: "Подходят фото (JPG, PNG, HEIC) и PDF",
    addFiles: "Добавить фото",
    dragDrop: "Перетащите файлы сюда или нажмите",
    maxFiles: "Макс. 10 файлов",
    maxSize: "Макс. 10 МБ на файл",
    scoreChip: "{score} из {max} · {percent}%",
  },

  reports: {
    empty: "Пока мало данных. Графики появятся после первых проверенных ДЗ",
    hwAverage: "Средний процент ДЗ по неделям",
    mockExams: "Пробные экзамены",
    onTime: "Сдано в срок",
    lastResult: "Последний результат: {value}",
  },

  student: {
    profile: "Профиль",
    class: "Класс",
    timezone: "Часовой пояс",
    webLogin: "Войти в браузере",
    webLoginHint: "Открой приложение через бота или используй ссылку входа",
    logout: "Выйти",
  },

  admin: {
    saveSuccess: "Сохранено",
    lessonOverlap: "В этом времени уже есть урок",
    extensionLimit: "Дедлайн уже переносили 2 раза",
    confirmCancel: "Отменить урок {date}, {time}? Ученики получат уведомление",
    confirmArchive: "Архивировать ученика? Данные и статистика сохранятся",
    inviteCreated: "Ссылка создана. Действует 7 дней, откроется один раз",
    emptyStudents: "Учеников пока нет. Создайте первый профиль",
    emptyReviewQueue: "Очередь пуста. Всё проверено",
    emptySchedule: "Расписание пусто",
    emptyHomework: "Домашних заданий нет",
    emptyCatalog: "Каталог пуст",
    emptyFinance: "Нет финансовых данных",
    tabs: {
      overview: "Обзор",
      lessons: "Уроки",
      homework: "ДЗ",
      exams: "Пробники",
      finance: "Финансы",
    },
    student: {
      name: "Имя",
      class: "Класс",
      subjects: "Предметы",
      timezone: "Часовой пояс",
      price: "Цена занятия",
      videoUrl: "Ссылка Телемост",
      boardUrl: "Ссылка доски",
      notes: "Заметки преподавателя",
      parentContact: "Контакт родителя",
      invite: "Приглашение",
      archive: "Архивировать",
      restore: "Восстановить",
      edit: "Редактировать",
      new: "Новый ученик",
    },
    lesson: {
      subject: "Предмет",
      participants: "Участники",
      time: "Время",
      duration: "Длительность",
      topic: "Тема",
      videoOverride: "Телемост (переопр.)",
      boardOverride: "Доска (переопр.)",
      create: "Создать урок",
      edit: "Редактировать",
      reschedule: "Перенести",
      cancel: "Отменить",
      complete: "Завершить",
      attendance: "Посещение",
      billable: "Засчитать",
      priceSnapshot: "Цена (снимок)",
    },
    homework: {
      title: "Название",
      description: "Описание",
      kind: "Тип",
      maxScore: "Макс. балл",
      examType: "Тип экзамена",
      dueMode: "Срок",
      dueModeNext: "Следующее занятие",
      dueModeFixed: "Фиксированная дата",
      dueDate: "Дедлайн",
      materials: "Материалы",
      assignees: "Кому выдать",
      create: "Создать ДЗ",
      assign: "Выдать",
      review: "Проверить",
      grade: "Оценить",
      return: "На доработку",
      extend: "Перенести дедлайн",
      extensionsLeft: "Осталось переносов: {left} из 2",
      score: "Балл",
      comment: "Комментарий",
      reviewFiles: "Файлы проверки",
    },
    schedule: {
      template: "Шаблон",
      weekday: "День недели",
      startTime: "Время начала",
      duration: "Длительность",
      period: "Период",
      generate: "Сгенерировать",
      deactivate: "Отключить",
      preview: "Предпросмотр",
    },
    mockExam: {
      student: "Ученик",
      examType: "Тип экзамена",
      date: "Дата",
      primaryScore: "Первичный балл",
      maxPrimary: "Макс. первичный",
      geometry: "Геометрия (баллы)",
      converted: "Результат",
      scaleNA: "Шкала не применима (нестандартный максимум)",
    },
    finance: {
      earned: "Заработано",
      expected: "Ожидается",
      cancellations: "Отмены",
      period: "Период",
      groupBy: "Группировка",
      week: "Неделя",
      month: "Месяц",
      student: "Ученик",
      subject: "Предмет",
      exportCsv: "Экспорт CSV",
    },
    catalog: {
      title: "Название",
      description: "Описание",
      priceText: "Стоимость (текст)",
      published: "Опубликовано",
      order: "Порядок",
      create: "Добавить услугу",
    },
    staff: {
      name: "Имя",
      role: "Роль",
      invite: "Приглашение",
      archive: "Архивировать",
      create: "Добавить сотрудника",
    },
  },

  errors: {
    network: "Нет соединения. Проверь интернет и повтори",
    server: "Что-то пошло не так. Попробуй ещё раз",
    notFound: "Страница не найдена",
    forbidden: "Нет доступа",
    validation: "Проверьте правильность заполнения",
  },

  plural: {
    lesson: ["урок", "урока", "уроков"],
    homework: ["задание", "задания", "заданий"],
    student: ["ученик", "ученика", "учеников"],
    point: ["балл", "балла", "баллов"],
  },
};